name: 'transform'
version: '1.0.0'
config-version: 2

profile: 'transform'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

on-run-end:
  - "{{ print('PASS') }}"

models:
  transform:
    bronze:
      +materialized: view
      +schema: bronze
